### ISSUE TITLE
Cannot catch constant evaluation errors for dill files

### ISSUE THREAD

**Issue by jensjoha** [dart-archive/kernel_sdk#21]
If the ConstantEvaluator evaluates an error it reports "error evaluating constant constructor" (dil_to_il.cc) meaning that try/catch doesn't work. For instance:

```
main() {
  try {
    print(42 ~/ 0);
  } catch(e) {
    print("catch in main");
  }
}
```

When running this as a dart file I get the (expected) result

> catch in main

When running this as a dill file (compiled with dartk, not that I think it matter) I get 

> Unhandled exception:
> IntegerDivisionByZeroException
> # 0      int.~/ (dart:core-patch/integers.dart:28)
> # 1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
> # 2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
> 
> error: error evaluating constant constructor

Somewhat similarly

```
main() {
  try {
    print(4.2 << 2);
  } catch(e) {
    print("Catch in main");
  }
}
```

Gets me

> Catch in main

and

> Segmentation fault (core dumped)

for the dart and dill files, respectively.

This is also a problem in my current constant-fold transformation, that for instance transforms "1.unary-" into "-1" meaning that "1 >> -1" isn't caught either. Without the transformation this does work (i.e. I can catch it), but seemingly only because FlowGraphBuilder::VisitMethodInvocation doesn't go deep (as I read it it transforms "1 >> (1.unary-)" into "1 >> -1" --- and similarly for instance "1+2+3" into "3+3"?)

**Comment by mkustermann** [comment]
This might have been introduced recently by 16cd1c272bf9788bcf016f35d7f3600e3273e039 since it uses the constant evaluator even for non-const expressions.

Modifying the example slightly to be in const-context, the normal VM also doesn't throw an exception:

```
class A {
  final f;
  const A(this.f);
}

main() {
  try {
    print(const A(4.2 << 2));
  } catch(e) {
    print("Catch in main");
  }
}
```

/cc @mraleph

**Comment by mraleph** [comment]
Yeah, it's my bug. I will fix it.

**Comment by mraleph** [comment]
Fixed in d8837a0

**Comment by jensjoha** [comment]
The 

```
main() {
  try {
    print(4.2 << 2);
  } catch(e) {
    print("Catch in main");
  }
}
```

example still gets me 

> Catch in main

and

> Segmentation fault (core dumped)

for the dart and dill files, respectively.

**Comment by mraleph** [comment]
`ConstantEvaluator` does not correctly handle no-such-method sitatuations.
